java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/year-'yyyy'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --annual
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/month-'yyyyMM'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --monthly --date 20160930
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/month-'yyyyMM'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --monthly --date 20161031
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/month-'yyyyMM'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --monthly
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly --date 20160924
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly --date 20161001
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly --date 20161008
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly --date 20161015
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly --date 20161022
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly --date 20161029
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly --date 20161105
java -cp "h:/my documents/data/projects/viaf/viaf-crontab/target/viaf-crontab.jar;h:/my documents/data/projects/jsap/target/JSAP-2.3-SNAPSHOT.jar;h:/my documents/data/java/lib/freemarker-2.3.25-incubating.jar" org.oclc.crontab.VIAFReportConsolidator --htmlTemplateDirectory "z:/stats" --contentNameTemplate "'z:/abstractedAccessLogs/content-'yyyyMMdd" --reportNameTemplate "'z:/stats/week-'yyyyMMdd'.html'" --analyzers "VIAFSearches,UsageByIPAndVIAFURLType,UsageByIPAndFormat,UsageByVIAFURLType,VIAFBulkDownloads" --hostNameProperties hostNames.properties --weekly

